########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################

def build(bld):

    bld.CryEngineModule(

        # Settings
        target             = 'Cry3DEngine',
        vs_filter          = 'CryEngine',
        copyright_org      = 'Amazon-CryTek',
        file_list          = ['cry3dengine.waf_files'],
        pch                = 'StdAfx.cpp',
        platforms          = ['all'],
        configurations     = ['all'],
        use                = [ 'AzFramework' ],
        win_features       = ['crcfix'],
        win_includes       = [bld.Path('../3rdParty/voxigen/include'),
            bld.Path('../3rdParty/voxigen/FastNoiseSIMD'),
            bld.Path('../3rdParty/glm'),
            bld.ThirdPartyPath('mikkelsen')],
        win_x64_debug_lib           = ['voxigend', 'fastNoised'],
        win_x64_release_lib           = ['voxigen','fastNoise'],
        win_x64_debug_libpath       = [bld.Path('../3rdParty/voxigen/_buildx64/Debug'),
            bld.Path('../3rdParty/voxigen/_buildx64/FastNoiseSIMD/Debug')],
        win_x64_release_libpath     = [bld.Path('../3rdParty/voxigen/_buildx64/Release'),
            bld.Path('../3rdParty/voxigen/_buildx64/FastNoiseSIMD/Release')],
        win_cxxflags         = ['/W3'],

       

       

        # Testing
        test_all_file_list = ['cry3dengine_test.waf_files'],

    )
